name: 'Hello World'
description: 'Greet someone'
inputs:
  your-name:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.your-name }}
